### ISSUE TITLE
Typo3 9.5.15 Debug not working

### ISSUE THREAD

**Issue by droomdre** [cobwebch/external_import#119]
The documentation recommends devlog but this is not for Typo3 9 available. The Typo3 Logger also not working. I  get the following error:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function info() on null | Error thrown in file /home/.../typo3conf/ext/external_import/Classes/Importer.php in line 536. `

**Comment by fsuter** [comment]
OK, I'll need to check. The devlog is indeed not available anymore since TYPO3 v9 (the underlying devlog method was removed from the TYPO3 core).

**Comment by droomdre** [comment]
do i have any possibilities to debug on typo3 9.5.15? I actually have no records inserted with the same configuration and typo3 on my new system.

**Comment by fsuter** [comment]
The simplest way is to use the preview mode which presents relevant data for every step in the process. If that does not help, you need indeed to rely on the logging and the debug mode on the command line. I have just checked the code and I don't understand why the logger instance is null in your case. If I may ask a basic question: have flushed the whole cache, including the code cache (as you can do in the Maintenance backend module)? Because it looks like the injection of the logger instance does not take place and that could be due to upgrading the external_import version without flushing the code cache (and implementation of the logger class has changed in recent versions). HTH

**Comment by droomdre** [comment]
Yeah i did that a couple of time. I just found out after long debugging that is due to the "Force time limit" i have set in the settings. I've entered 3600 and the debug failed. Now i put back -1 and it's working. Can u confirm?

**Comment by fsuter** [comment]
Confirmed. This is sooo weird.

**Comment by fsuter** [comment]
Not so weird. It's a question of timing. Setting the time limit happens in the Importer constructor and it is logged as an information, but apparently the logger is not yet loaded. So I'll just drop the informational message.
