### ISSUE TITLE
Do not use uniqid for generating temporary keys

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [cobwebch/external_import#123]
Hi there,

when inserting new records into the table "sys_category" I get the following error:

---
Importing: sys_category / 1
---------------------------

 [ERROR] An exception occurred while saving the data:                           
         "tx_blog_category_NEW5eb53a93f2f2e4.30703292" is not a valid tag for a 
         cache entry. (code: 1233057360, location:                              
         /var/www/[instancename]/web/typo3/sysext/core/Classes/Cache/Frontend
         /AbstractFrontend.php at line 124)                                     

 [WARNING] The import was aborted. Please see the relevant messages.
---

the first record gets inserted, the following ones not because of the abort. After digging into the problem i found out that it is caused by the following code of the blog extension:

https://github.com/TYPO3GmbH/blog/blob/master/Classes/Hooks/DataHandlerHook.php#L74

The error doesn't show up when the blog extension is deactivated. I know the problem should probably be addressed there. But maybe you can confirm this or give me a hint what's going on here and how to avoid the error without tweaking the blog extension.

Thank you!

TYPO3 9.5.15
external_import 4.2.3
blog 9.1.2

**Comment by fsuter** [comment]
Hi. I think the problem can and should be addressed in external_import. This is related to the "NEW" keys that external_import generates for new records to be imported. It relies on the PHP function `uniqid` to generate a unique key, but this function returns a dot somewhere in the middle of its result. This is incompatible with the tag validation pattern defined by constant `\TYPO3\CMS\Core\Cache\Frontend\FrontendInterface::PATTERN_TAG` which excludes dots.

In a sense it is really no one's fault, but I can take care on the external_import side to generate a key that is compatible with the above-mentioned pattern.

That being said, the blog extension should not be clearing the cache for new records, because they will never have a cache entry anyway... This could be checked using the "status" parameter received by the hook.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Thank you very much for the awesome fast fix. The problem is solved now! :)

**Comment by fsuter** [comment]
🙌
