### ISSUE TITLE
Additional Fields missing from Configuration details

### ISSUE THREAD

**Issue by mbrodala** [cobwebch/external_import#154]
Since the upgrade to version 5.x of External Import "Additional Fields" are not rendered anymore. Of course, the option has been migrated to the new location.

There are two errors here:

1. `additionalFields` is checked via `generalConfiguration.additionalFields` instead of `configuration.additionalFields`:
  https://github.com/cobwebch/external_import/blob/5.0.1/Resources/Private/Partials/DataModule/GeneralConfigurationTab.html#L160
2. `additionalFields` is now an array, so even fixing the first error would only output `Array` instead of the list of fields like before. so either iteration and output with linebreaks or a custom array implode/join would be necessary here.

**Comment by fsuter** [comment]
Oh dear, that seems so obvious! How could I miss it? :no_mouth:

**Comment by fsuter** [comment]
Ah no, sometimes writing makes the brain work. The information appears in the Columns mapping tab now, since additional fields are handled like ordinary mapped columns (except they are not saved). So it is just a question of removing the mention of "additionalFields" in the General configuration tab (unless the old property is still used, in which case it shows a deprecation message).

**Comment by mbrodala** [comment]
Indeed, you are right. I didn't check that tab. So I'd suggest to display a text like _See "Columns mappings" tab_ all the time until the backward layer is dropped. The warning about legacy format could be displayed next to this.
