### ISSUE TITLE
Error: Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAssociative()

### ISSUE THREAD

**Issue by uv21** [cobwebch/external_import#214]
After upgrading from Typo3 9.5 to 10.4 the data import in BE does not work anymore. In 9.5 we use external_import 5.1.1 in Typo3 10.4 it is external_import 6.0.1

Error message: 
**Error: Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAssociative()**

Administration log in BE shows this:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAssociative() | Error thrown in file /var/www/homepage/typo3conf/ext/external_import/Classes/Domain/Repository/UidRepository.php in line 103. Requested URL: https://xxx.xx/typo3/index.php?route=%%2Fmodule%%2FExternalImportExternalimport%%2FExternalImportExternalImport&token=--AnonymizedToken--&tx_externalimport_externalimportexternalimport_externalimportexternalimport%%5Btable%%5D=tx_sfeventmgt_domain_model_event&tx_externalimport_externalimportexternalimport_externalimportexternalimport%%5Bindex%%5D=0&tx_externalimport_externalimportexternalimport_externalimportexternalimport%%5Baction%%5D=synchronize&tx_externalimport_externalimportexternalimport_externalimportexternalimport%%5Bcontroller%%5D=DataModule

We use a normal installation (no composer!)
Can someone help?

**Comment by fsuter** [comment]
Hi,
I'm not sure what can be done about this. Since you are not using composer, what this would seem to mean is that TYPO3 10.4, as a package, is shipped with a somewhat old version of doctrine/dbal, which does not yet have these new methods of accessing the results of a request. This is pretty surprising however, since the old method (`fetch`) has been deprecated for a while.

What you could try to do is check which version of doctrine/dbal TYPO3 10.4 actually supports, which version is packaged with TYPO3 10.4 and see if you can update just this component, by replacing it in the `vendor` directory (and you would need to "Rebuild PHP Autoload Information" from the Maintenance module after that). But this is tricky and could have side effects.

An alternative would to XCLASS each class of External Import which uses `fetchAssociative`. This is definitely safer.

I hope this helps you a bit.

**Comment by ineswillenbrock** [comment]
It seems to be doctrine/dbal 2.10.4 (according to typo3_src/vendor/doctrine/dbal/lib/Doctrine/DBAL/Version.php)

Would it make sense to raise the TYPO3 Version to 11 for external_import 6.x? That one ships 2.15.3

**Comment by fsuter** [comment]
Thanks for the information. I'm reluctant to change TYPO3 compatibility range in an existing branch. I would need to raise the major version number. At the same time I would like to keep compatibility with v10.

Maybe I'll check where `fetch` is called and do some compatibility check at that point.

**Comment by Treedent** [comment]
TYPO3 V10.4.31 non composer Install.
When using Backend Add Synchronisation settings
The same error still remaining in typo3conf/ext/external_import/Classes/Domain/Repository/SchedulerRepository.php
Line 153 : ->fetchAllassociative is hard coded.
