### ISSUE TITLE
extended News - new Fields not eligible for mapping

### ISSUE THREAD

**Issue by lgt** [cobwebch/external_import#227]
Hi,

After extendig `tx_news_domain_model_news`with custom fields I try to map on import those. But the new created fields are not getting recognized by mapper.

my config which relays in `TCA/Overrides/tx_news_domain_model_news.php` and looks as it follows

`$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['link_external']['external'] = [
    'news' => [
        'field' => 'tx_newsrundbrief_ext_link'
    ],
];`

I'm using version `5.1`

but the field is not getting mapped. Sorry for the question but I do not really have a big experience in this case can you provide me some support?

**Comment by fsuter** [comment]
Hi. With just that information it is impossible to say what is going wrong for you. However in general, the main culprit is the loading order of extensions (in this case the loading order of extension "news" and any other extension extending "news"). Since External Import configuration is based on the TCA, the best way to check if your configuration is loading as expected is to use the Configuration module in the TYPO3 backend and check the TCA of table `tx_news_domain_model_news`.

The next step is to make sure that your External Import configuration is correct, which you can check using the Data Module, provided by the extension.

If this does not help you, I would need more information, namely for a start:

- the full TCA configuration for External Import, including the general configuration (in your posting, you just mention one column)
- a sample of the data that you are trying to import

**Comment by lgt** [comment]
Hi @fsuter, thank you for the hints. The problem is solved now by setting up the right loading order of custom extensions.
