### ISSUE TITLE
_cli_ user not used with Scheduler Task

### ISSUE THREAD

**Issue by lauralang** [cobwebch/external_import#261]
First of all, thank you for the great Extension. I have one question. There is a screenshot with logfiles in your docs, showing that _cli_ User excuted the Import. I've registered an import as an automatic Import and every time I start it via Scheduler, there is no user shown (just "-" or my own username) and it does not update any of my fields. There is no error thrown either, just as if there was no change found. However, if I click the synchronize button on the Extension Tab, the table is updated and everythings works as expected.

It seems to me like there a access problems, but usually with _cli_ user I shouldn't have these, following the docs. Do I have to register the _cli_ user somewhere first for it to be used with the import via Scheduler?

Thank you very much in advance!

**Comment by fsuter** [comment]
Hi. This is weird. If you execute the task manually from the Scheduler, it should register with your user. The user `_cli_` should appear when the Scheduler is run via a cron job or when you use the command-line (`vendor/bin/typo3 externalimport:sync [arguments]`) to run the data synchronisation.

Unless you are running a very old version of TYPO3, there should be no access problem, since the `_cli_` user is auto-created as admin since a long time (not sure when it started, maybe with TYPO3 6.2).

The issue there could be is if you run the import manually from the backend with a non-admin user. In such a case, you need to check that said user has the right to write into the targeted tables.

If nothing of this corresponds to your scenario, I would try activating the debug mode and logging all the information possible. See: https://docs.typo3.org/p/cobweb/external_import/6.2/en-us/Installation/Configuration/Index.html#installation-configuration

**Comment by lauralang** [comment]
Thank you for your quick response.

If I type in `vendor/bin/typo3 externalimport:sync --table=fe_users --index=1` or `vendor/bin/typo3 scheduler:run` my log looks like this:

<img width="440" alt="grafik" src="https://user-images.githubusercontent.com/39274882/208894084-4a1039c1-c76e-4cd8-9cff-97298d8ac343.png">

If `scheduler:run` is executed by cronjob, there is the same user shown (-).

`vendor/bin/typo3 externalimport:sync --table=fe_users --index=1 --preview='Cobweb\ExternalImport\Step\TransformDataStep'` shows the expected data. But if I actually execute it, it doesn't update the data.

If I click the schduler play button, my user is shown. In my understanding it should work as well with my user, because I'm a Admin/Sytem Maintainer. But no data is updated.

The only way my data is updated is via synchronize button in the External Import Tab.

I'm not sure which additional information I could debug...

**Comment by lauralang** [comment]
Nevermind, there was a different problem. I'm using an EventListener for inserting the last executed time of my scheduler task into the uri of my API Call. I thought, I could set the timezone in order to not worry about formatting the date to my timezone. Turns out, without that my data is updated. Not sure, why the preview works but not the actual import.

Nevertheless, thank you very much!

**Comment by fsuter** [comment]
Glad that you found out what the problem was.
