### ISSUE TITLE
How to set default category

### ISSUE THREAD

**Issue by marexx** [cobwebch/external_import#275]
I import Data from different Data Sources in JSON Format as "news-item",
How can i set each NewsItem a default Category, depending on the Data Source.

**Comment by fsuter** [comment]
You can set a fixed value using the `value` transformation property: https://docs.typo3.org/p/cobweb/external_import/6.3/en-us/Administration/Transformations/Index.html#value

Since I suppose that you have a different configuration for each Data Source, you can set a different value each time.

Does that fit your scenario?

**Comment by marexx** [comment]
thnx. that's it
