### ISSUE TITLE
Interface "TYPO3\CMS\Reactions\Reaction\ReactionInterface" not found

### ISSUE THREAD

**Issue by linawolf** [cobwebch/external_import#298]
I just installed cobweb/external_import (7.1.1) on TYPO3 v 12.4.6 and after Installing I get the error 

```
Interface "TYPO3\CMS\Reactions\Reaction\ReactionInterface" not found

in /var/www/html/vendor/cobweb/external_import/Classes/Reaction/ImportReaction.php line 34
``` 
The class tries to implement this interface, however the exstensions composer.json does not require `typo3/cms-reactions`

**Comment by fsuter** [comment]
That's a tough one. The extension can't require `typo3/cms-reactions` because it's meant to remain compatible with TYPO3 11 for now. What I can do for now is add a note in the Installation chapter of the documentation.

Later, when compatibility with TYPO3 11 is dropped, the requirement can be added.

**Comment by akiessling** [comment]
Sorry for opening a duplicate :/ 
My initial problem was the wrongly created table sys_reaction from an update deployment  with database:updateschema 

```
Incorrect table definition; there can be only one auto column and it must be defined as a key
Key column 'uid' doesn't exist in table
```

I removed the extension since we won't need it otherwise and i ended up with the other error --> then had to remove the table manually and recreate it with the update wizard. 

Maybe the external_import_configuration field can be added through the AlterTableDefinitionStatementsEvent event if the reactions extension is installed + TCA would also need a check for ExtensionManagementUtility::isloaded('reactions') and we should be good to go? I disabled the sql, wrapped the TCA with the condition and removed the reactions extension -> no error.  

Adding it to _suggests_ should then be enough vor > v12?

**Comment by fsuter** [comment]
I agree that the current state can create quite a mess. Thanks for suggesting the various elements that can improve the situation. I'll take a look.

**Comment by akiessling** [comment]
Would you like me to come up with a pull request?

**Comment by fsuter** [comment]
Pull requests are always welcome and definitely improve the chances of the bug being fixed ;-) Thanks for the proposal.

**Comment by akiessling** [comment]
Oh my, i had it on my todo list but could not find any spare time :/ thanks for taking care!
