### ISSUE TITLE
Property "setColumnIndex" is set to %1$s, but no matching configuration exists for table %2$s.

### ISSUE THREAD

**Issue by opi99** [cobwebch/external_import#3]
I've an issue with this error from the ControlConfigurationValidator:

1.) The property is useColumnIndex (not set)
2.) It tries to test if the value of that property is found as configuration key themselves? But why should I name a configuration with same name as the value of useColumnIndex of one of my configurations. In my example I would need a configuration called "myImportColumn"
Example:

```array(14) {
  'Foo' =>
  array(12) {
    'connector' =>
    string(4) "feed"
    'parameters' =>
    array(1) {
      'uri' =>
      string(69) "http://myurl"
    }
    'data' =>
    string(3) "xml"
    'nodetype' =>
    string(4) "myNode"
    'referenceUid' =>
    string(5) "myId"
    'pid' =>
    int(39)
    'enforcePid' =>
    bool(true)
    'description' =>
    string(11) "myDescription"
    'priority' =>
    int(20)
    'useColumnIndex' =>
    string(17) "myImportColumn"
    'clearCache' =>
    string(35) "5,63,71,72,73,74,75,511,529,527,528"
  }
  'Bar' =>
  array(12) {
    'connector' =>
    string(4) "feed"
    'parameters' =>
    array(1) {
      'uri' =>
      string(64) "http://myurl"
    }
    'data' =>
    string(3) "xml"
    'nodetype' =>
    string(4) "myNode"
    'referenceUid' =>
    string(5) "myId"
    'pid' =>
    int(38)
    'enforcePid' =>
    bool(true)
    'description' =>
    string(11) "myDescription"
    'priority' =>
    int(20)
    'useColumnIndex' =>
    string(17) "myImportColumn"
    'clearCache' =>
    string(39) "112,135,136,134,133,132,130,508,534,533"
  }```

This worked in versions before 3.0 and it also works if I disable the validateUseColumnIndexProperty test.

**Comment by fsuter** [comment]
Sorry for late reply. I was away for a week. I don't understand what your problem is. You first mention that "useColumnIndex" is not set, then your code example makes use of that property. Could you try explaining again please?

**Comment by opi99** [comment]
Hi,

no at first I say, that it is called "useColumnIndex" and not "setColumnIndex" (as stated in the error message).

**Comment by fsuter** [comment]
Ah ok, now I understand your first remark. Indeed, the property's name is wrong in the error message.

About your second remark, indeed your example configuration will trigger an error, because your configurations are defined using keys "Foo" and "Bar", but the "useColumnIndex" property refers to a (non existing) key "myImportColumn". The whole point of the "useColumnIndex" property is that you can refer to another import configuration, by defining a separate configuration in the "ctrl" part of the TCA without having to define an external import configuration for each column.

If you don't need to refer to another configuration, simply don't set "useColumnIndex".

It worked before 3.0 because no validation of the external import configuration happened. In that sense, version 3.0 is more strict, but also more helpful, because it detects errors or nonsensical properties.

Or am I misunderstanding you completely?

**Comment by opi99** [comment]
Hi,

implemented was this feature in https://github.com/cobwebch/external_import/commit/70b40ef06b4e3fb17b00b2d4380656e2a910ff2d
Also the description says 
```
The "ctrl" part has to exist with its own index, but the columns may refer
 to another index and thus their configuration does not need to be defined.
```
With "useColumnIndex you define an index to be taken for the columns and not as configuration index in the "ctrl" section (which do not make any sense).

In your words you describe more a function which would be named like "useConfiguration" but thats not what the source do.

So the 3.0 version validates something which do not need to exists.

**Comment by fsuter** [comment]
Sorry for the delay, I was pretty busy. And I'm still not sure I understand what you mean.

Although this property is defined in the "ctrl" part, it is used at column-level. It means that, for this configuration, the key/index to use to find individual column configurations is different.

This shows an example: https://github.com/fsuter/externalimport_test/blob/master/Configuration/TCA/tx_externalimporttest_product.php

Products are imported from several files. The information in the "ctrl" section varies, but all columns are mapped the same way. Hence the "more" and "stable" configurations define the "base" key as the reference for their columns.

I agree that the description in the manual is not very clear. I could update it with the example from the externalimport_test extension which should make things clear hopefully.

Is it more clear for you?

**Comment by opi99** [comment]
Please do not change the documentation, change the source code to work as it was documented.

You can test your example, remove the check and remove the 'base' definition in ctrl section (as the data won't be used somewhere) and you will see, it works like a charm.

You don't need the base 'ctrl' as the data in it is irrelevant everywhere.
(BTW. if the base config do not exists, nobody can accidentally select it in backend, which is a big win then).

**Comment by fsuter** [comment]
Duh?

Of course the "base" configuration is used. Why would I want to remove it?

I'm sorry, but I can't make sense of what you say :-(

**Comment by fsuter** [comment]
Ah, I think I've finally got what you mean. From your interpretation the "useColumnIndex" property would refer to an index used only for columns and which has no corresponding "ctrl" part. Some kind of "abstract" column configuration in a sense.

From my intention when I implemented the feature, there is always some basic configuration which exists for both "ctrl" and "column" parts and which is somehow "copied" to additional configurations, where the "ctrl" part needed to be changed, but not the "column" parts. Hence for me, it makes total sense to check for a "ctrl" part corresponding to the value of the "useColumnIndex" property, which is why I implemented the validation as it is now.

And actually the example I have referred you to works exactly in that way, because the "base" configuration is indeed used and not just some dummy placeholder.

So I can see two ways to proceed from here: either I make the documentation more explicit, so that it is clear that a "ctrl" configuration is needed. Or the code is changed to allow for the existence of a column configuration without corresponding "ctrl" part, which would exist just to be referenced from the "useColumnIndex" property.

Does that make sense for you too?

**Comment by opi99** [comment]
Now you got it. :-)

And the documentation clearly says

> to another index and thus their configuration does not need to be defined.

I don't need to define one.


What you describe with `which is somehow "copied" to additional configurations` does not happen anywhere in the source. The "ctrl" config of "base" is never used or merged into the "ctrl" config of "more" or "stable". BTW. in your example all things in "ctrl" are overwritten.

**Comment by fsuter** [comment]
Forget about "copy". It was a kind of metaphor, but it obviously works only for me ;-)

I'll indeed change the validator: it should still exist, but check that there's an existing column configuration with the defined key.

**Comment by opi99** [comment]
Ok, would be fine with me
