### ISSUE TITLE
Importing data to news categories

### ISSUE THREAD

**Issue by mwext** [cobwebch/external_import#47]
Hello, 

I am not too sure this is a bug, however I think this is worth mentioning and also your help would be appreciated if this is indeed not a bug.

I have one extension, which extends news ext. This extension pulls data from external site and inserts in tx_news_domain_model_news table. 

The problem is: since news 3.x version, the extension is not using its own table (tx_news_domain_model_category), but sys_category. 

So I changed the TCA from 

```
$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['categories']['external'][43] = array(
	  'value' => '51',	//uid der kategorie, 
      'MM' => array(
        'mapping' => array(
                'table' => 'tx_news_domain_model_category',
                'referenceField' => 'uid',
        ),
    
    )
);
```
To: 

```
$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['categories']['external'][43] = array(
	  'value' => '51',	//uid der kategorie, 
      'MM' => array(
        'mapping' => array(
                'table' => 'sys_category',
                'referenceField' => 'uid',
        ),
    
    )
);
```
(only table value changed)

When I try to sync the data, I get OK messages, that show, that some records and were updated and some new ones were inserted. 

However if I check with sql: `SELECT * FROM 'sys_category_record_mm' WHERE uid_local = 43`, the number of records is still the same - nothing new added.

**Comment by fsuter** [comment]
Indeed the whole thing with MM relations is not simple. I guess you have read that chapter: https://docs.typo3.org/typo3cms/extensions/external_import/User/MappingData/Index.html#user-mapping-data-mm (especially the first bit, before the example, which maybe does not help...).

Anyway the thing is that, in your case, you don't need to do explicit mapping. The `categories` field of table `tx_news_domain_model_news` "knows" that it is related to the `sys_category` table, thanks to its TCA definition. All you need to ensure is that External Import prepares the right value(s) in this field.

As I understand your example, you have a fixed value of `51`. So your configuration should include only that, i.e.

```
$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['categories']['external'][43] = array(
	  'value' => '51',	//uid der kategorie, 
);
```

The `DataHandler` class will receive the value `51` and will automatically create relations in the `sys_category_record_mm` table.

**Comment by mwext** [comment]
Thank you for the help and quick reply! 

Now I seem to be getting the categories, however I need to test a bit more, to see if I get the desired result.

**Comment by fsuter** [comment]
Yes sure, test all you need and ask further questions if needed. When you're done, please report here, so that I know I can close the issue.

**Comment by fsuter** [comment]
May I close this issue?

**Comment by in-session** [comment]
Hi,

first many thanks for the great EXT.

I have the same problem to mapping the categories of the news, have you a chance to make an advance example for it?

The XML feed have the follow syntax:
<item>
....
<category>CATNAME1</category>
<category>CATNAME2</category>
</item>

Now we need to map as follow:
'CATNAME1' in tx_news_domain_model_news.categories = 1
'CATNAME2' in tx_news_domain_model_news.categories = 2

So after import the tx_news_domain_model_news.categories need the follow content= 1,2

Many Thanks Chris

**Comment by fsuter** [comment]
Hi Chris. Could you post an extract of the XML feed you are trying to import? The exact structure makes a difference about how to handle things. I can't answer you otherwise.

**Comment by in-session** [comment]
Hi, yes of course! 

attached is a rendered file of the default news RSS.
Now the idea is to map as example the "categorie 1" and give them a a specified numer inside the database table tx_news_domain_model_news.categories

RSS item 2: Example: "categorie 1" = 1, "categorie 10" = 50 ~  tx_news_domain_model_news.categories = 1,50
RSS item 2: Example: "categorie 2" = 60, "categorie 10" = 50 ~  tx_news_domain_model_news.categories = 50,60

I hope you understand what I mean that?

[rss.zip](https://github.com/cobwebch/external_import/files/1700067/rss.zip)

**Comment by fsuter** [comment]
Thanks for the additional info.

Your scenario is complex, because you may have more than one `<category>` tag per `<item>` tag. External Import expects a single tag in every structure and will map that tag to a database field. What you need to do is to manipulate the data before External Import starts to do any real processing on it.

IMO the best way would be to use the `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['svconnector_feed']['processXML']` hook of extension "svconnector_feed", which will let you manipulate the XML (the hook will receive it as a string and is expected to return a modified string).

In this hook you could read all `<category>` tags for each `<item>` and create a new `<categories>` node, with a comma-separated list of categories. Then your structure will be something like:
```
        <item>
            <guid isPermaLink="false">news-6864</guid>
            <pubDate>Tue, 06 Feb 2018 15:36:55 +0100</pubDate>
            <title>title</title>
            <link>https://www.domain.com/news/detail/news.html</link>
            <description>desc</description>
            <enclosure url="https://www.domain.com/fileadmin/news/_processed_/b/1/173a90d351.jpg" length="800" type="image/jpeg" />
            <content:encoded>
                <![CDATA[<p><strong>content</strong></p>]]>
            </content:encoded>
            <category>categorie 1</category>
            <category>categorie 10</category>
            <categories>categorie 1,categorie 10</categories>
        </item>
```

In External Import you would map the "categories" field and not "category". You will need to make use of two properties:
* multipleValuesSeparator: this will split your values on the comma and map each of them
* valueMap: since you have fixed values, you will assemble a fixed map, something like:
```
[
    'categorie 1` => 23,
    'categorie 10` => 65,
]
```

that will map each category name in the XML file to a category uid in the TYPO3 database.

I hope this will help you on your path. It is not the simplest scenario that you are facing.

**Comment by in-session** [comment]
Great many thanks for the information and sorry for my mistake. i allready use the svconnector_feed like your example:  https://docs.typo3.org/typo3cms/extensions/externalimport_tut/RssImport/Data/Index.html 

I will test it ASAP and send you an feedback and a code sniped for all other :-)

An other small question is: I test the RssImport, but each import task make a dublicate news (new copy of the news).
What do you mean is the best way to update the news only if changed based on the pubDate?

**Comment by fsuter** [comment]
This sounds like you have not defined a proper external id (and you have disabled the "delete" operation).

You need to make sure that the field pointed by the `referenceUid` property is really unique in the imported data. If not, existing copies will not be detected and updated. Instead new copies will be created. If, on top of this, you have disabled the "delete" operation (as is the case in the example), copies will accumulate.

It is up to you to know whether it makes sense to disable the "delete" operation or not. The main idea in the example, is that a RSS feed will contain only the latest news. Thus if you want your site to accumulate all news over time, you disable the "delete" operation in order to preserve news locally once they are gone from the RSS feed. Instead, if you wish your site to reflect only the news from the RSS feed, you should let the "delete" operation happen, so that old news are cleaned up.

But if you get multiple copies as you describe, you had better adjust your `referenceUid` handling before enabling the "delete" operation, because the cleanup will let you believe that you have solved your issue, which will not be the case.

HTH

**Comment by in-session** [comment]
Hi, you're right. I changes now the 'referenceUid' => 'import_id' this is a default field of EXT:news.

`
$GLOBALS[ 'TCA' ][ 'tx_news_domain_model_news' ][ 'columns' ][ 'import_id' ][ 'external' ] = [
    0 => [
        'field' => 'guid'
    ]
];
`
Is there a way for the field to insert an append or prefix?
If different RSS are included, it would be good to include a fixed part for each RSS-File inside the field 'import_id'.


I changed actuell the default RSS Feed of the EXT:news:
`
<f:if condition="{newsItem.categories}">
            <categories>
              <f:for each="{newsItem.categories}" as="newsItemCategory" iteration="iterator">
                <f:if condition="{iterator.isLast}">
                  <f:then>{newsItemCategory.title -> f:format.htmlspecialchars()}</f:then>
                  <f:else>{newsItemCategory.title -> f:format.htmlspecialchars()},</f:else>
                </f:if>
              </f:for>
            </categories>
            <categoriesCount><f:count>{newsItem.categories}</f:count></categoriesCount>
          </f:if>
`

output:
`
<category>Cat1</category>
<category>Cat2</category>
<categories>Cat1, Cat2</categories>
<categoriesCount>2</categoriesCount>
`

The categoriesCount needs to insert in the table tx_news_domain_model_news->categories
`
$GLOBALS[ 'TCA' ][ 'tx_news_domain_model_news' ][ 'columns' ][ 'categories' ][ 'external' ] = [
    0 => [
        'field' => 'categoriesCount'
    ]
];
`

Now I'm just trying to insert the news in the table sys_category_record_mm.
I'll keep you up to date, maybe we'll get a good tutorial of the EXT: news.

**Comment by fsuter** [comment]
You can append or prepend a field with pretty much anything you want, but you need to write a user function for this. The prefix or suffix could be a parameter of the function, making it possible to have a different string for each import.

**Comment by fsuter** [comment]
BTW you shouldn't need to insert records into sys_category_record_mm yourself. If your import of news contains categories relations, the entries in sys_category_record_mm will be created automatically by the DataHandler when invoked in the storage step of External Import.

**Comment by in-session** [comment]
Hi, many thanks, I already found out :-)

the current situation is that I insert two new columns inside the tx_news_domain_model_news for storage the image and url data.

```
CREATE TABLE tx_news_domain_model_news (
    external_imp_image varchar(512) DEFAULT '' NOT NULL,
    external_imp_url varchar(512) DEFAULT '' NOT NULL
);
```

And the current code whiche works actuell:

```
$GLOBALS[ 'TCA' ][ 'tx_news_domain_model_news' ][ 'ctrl' ][ 'external' ] = [
	0 => [
		'connector' => 'feed',
		'parameters' => [
			'uri' => 'http://www.domain.com/rss.xml'
		],
		'data' => 'xml',
		'nodetype' => 'item',
		'referenceUid' => 'import_id',
		'enforcePid' => true,
		'priority' => 200,
		//PID of Sysfolder
		'pid' => 33,
		'disabledOperations' => 'delete',
		'description' => 'External Import'
	],
];
$GLOBALS[ 'TCA' ][ 'tx_news_domain_model_news' ][ 'columns' ][ 'import_id' ][ 'external' ] = [
	0 => [
		'field' => 'guid'
	]
];


$GLOBALS[ 'TCA' ][ 'tx_news_domain_model_news' ][ 'columns' ][ 'title' ][ 'external' ] = [
	0 => [
		'field' => 'title'
	]
];

$GLOBALS[ 'TCA' ][ 'tx_news_domain_model_news' ][ 'columns' ][ 'external_imp_image' ][ 'external' ] = [
	0 => [
		'field' => 'enclosure',
		'attribute' => 'url'
	]
];


$GLOBALS[ 'TCA' ][ 'tx_news_domain_model_news' ][ 'columns' ][ 'external_imp_url' ][ 'external' ] = [
	0 => [
		'field' => 'link'
	]
];

$GLOBALS[ 'TCA' ][ 'tx_news_domain_model_news' ][ 'columns' ][ 'datetime' ][ 'external' ] = [
	0 => [
		'field' => 'pubDate',
		'transformations' => [
			10 => [
				'userFunc' => [
					'class' => \Cobweb\ ExternalImport\ Transformation\ DateTimeTransformation::class,
					'method' => 'parseDate'
				]
			]
		]
	]
];

$GLOBALS[ 'TCA' ][ 'tx_news_domain_model_news' ][ 'columns' ][ 'teaser' ][ 'external' ] = [
	0 => [
		'field' => 'description'
	]
];

$GLOBALS[ 'TCA' ][ 'tx_news_domain_model_news' ][ 'columns' ][ 'bodytext' ][ 'external' ] = [
	0 => [
		'field' => 'encoded',
		'transformations' => [
			10 => [
				'rteEnabled' => true
			]
		]
	]
];

$GLOBALS[ 'TCA' ][ 'tx_news_domain_model_news' ][ 'columns' ][ 'type' ][ 'external' ] = [
	0 => [
		'transformations' => [
			10 => [
				'value' => 0
			]
		]
	]
];

$GLOBALS[ 'TCA' ][ 'tx_news_domain_model_news' ][ 'columns' ][ 'hidden' ][ 'external' ] = [
	0 => [
		'transformations' => [
			10 => [
				'value' => 0
			]
		]
	]
];

$GLOBALS[ 'TCA' ][ 'tx_news_domain_model_news' ][ 'columns' ][ 'categories' ][ 'external' ] = [
	0 => [
		'field' => 'categories',
		'transformations' => [
			10 => [
				'mapping' => [
					'multipleValuesSeparator' => ',',
					'valueMap' => [
						'Cat1' => 35,
						'Cat2' => 41,
						'Cat3' => 42
					],
				]
			]
		]
	]
];

$GLOBALS[ 'TCA' ][ 'tx_news_domain_model_news' ][ 'columns' ][ 'author' ][ 'external' ] = [
	0 => [
		'xpath' => '//channel/title'
	]
];
```

I'm still thinking about integrating the pictures via FAL.

Greetings

**Comment by in-session** [comment]
BTW the example of the tutorial "Importing related links" I think this have an error, but that is current not relevant to me.
The import works but we have inside the tx_news_domain_model_link.sorting repeatedly different numbers in three digits. However, the number combinations did not make sense after the import.

```
$GLOBALS['TCA']['tx_news_domain_model_link']['ctrl']['external'] = [
        0 => [
                'connector' => 'feed',
                'parameters' => [
                        'uri' => 'http://typo3.org/xml-feeds/rss.xml'
                ],
                'data' => 'xml',
                'nodetype' => 'item',
                'referenceUid' => 'uri',
                'enforcePid' => true,
                'priority' => 210,
                'disabledOperations' => 'delete',
                'description' => 'Import of typo3.org news related links'
        ],
];
$GLOBALS['TCA']['tx_news_domain_model_link']['columns']['title']['external'] = [
        0 => [
                'field' => 'title'
        ]
];
$GLOBALS['TCA']['tx_news_domain_model_link']['columns']['uri']['external'] = [
        0 => [
                'field' => 'link'
        ]
];
$GLOBALS['TCA']['tx_news_domain_model_link']['columns']['parent'] = [
        'config' => [
                'type' => 'passthrough',
        ],
        'external' => [
                0 => [
                        'field' => 'link',
                        'transformations' => [
                                10 => [
                                        'mapping' => [
                                                'table' => 'tx_news_domain_model_news',
                                                'referenceField' => 'external_imp_url'
                                        ]
                                ]
                        ]
                ]
        ]
];
```

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Hi,

I tried to map categories from tx_sfeventmgt_domain_model_event records, but it's not working. The mapping definition is

$GLOBALS['TCA']['tx_sfeventmgt_domain_model_event']['columns']['category']['external'] = [
    0 => [
        'field' => 'categories',
    ],
];

where 'categories' is a list of comma separated category UIDs. This should work out of the box due to the TCA definition.

The problem I spotted: Unlike with EXT:news which has it's own definition for MM relations, ['TCA']['tx_sfeventmgt_domain_model_event']['columns']['category'] seems to be set/overwritten by the core (with MM relation definitions) and so ['TCA']['tx_sfeventmgt_domain_model_event']['columns']['category']['external'] is not there when I look in the backend-configuration of the TCA. ['external'] mapping definitions of all other fields are there.

I believe external TCA must be included after the core does its magic. Or what do you think how this can be solved?

**Comment by fsuter** [comment]
From what you say, this seems to be indeed a problem of TCA loading order. I think it should be safe if you can ensure that your "external" definition happens after "tx_sfeventmgt_domain_model_event". Normally your "external" TCA should be in a custom extension of your own and this extension should have a dependency of "sf_eventmgt", so that your extension is loaded after "sf_eventmgt".

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Indeed the dependency in our own extension was missing. Thanks a lot for the hint, François!
