### ISSUE TITLE
Error in svconnector_feed regarding use of absolute paths

### ISSUE THREAD

**Issue by bendoo** [cobwebch/external_import#58]
I noticed a change in svconnector_feed-extension which broke my set-up.

I always used this config:
$absolutePath='/www/436590_70794/rp-hosting/5150001/6150001/upload/xml/products/';

// Add the external information to the ctrl section
$GLOBALS['TCA']['tx_legamaster_domain_model_legamaster']['ctrl']['external'] = array();
$GLOBALS['TCA']['tx_legamaster_domain_model_legamaster']['ctrl']['external']['tr_en'] = array(
    'connector' => 'feed',
    'parameters' => array(
        'uri' => $absolutePath.'vc_en.xml'
    ),
    'data' => 'xml',
....

But it seems that the latest version can't read correctly the absolute path anymore.
If I change the path to:
$absolutePath='fileadmin/legamaster/xml/';
...this config works fine.

I did a temporary fix by symlinking fileadmin/legamaster/xml/ to the absolute path but I would prefer to put the path directly.

**Comment by fsuter** [comment]
I'm getting back to this belatedly. Actually this issue is related to "svconnector", not "external_import". Would you be so kind as to reopen this issue in the right project? This would be very helpful. Moving issues in GitHub doesn't seem to be possible. The right place would be: https://github.com/cobwebch/svconnector/issues

Thanks a lot.

**Comment by fsuter** [comment]
Thanks for moving the issue. Reference: https://github.com/cobwebch/svconnector/issues/10
