### ISSUE TITLE
Uncaught exception when parsing HTML

### ISSUE THREAD

**Issue by chris007mi6** [cobwebch/external_import#63]
Whenever I tried xmlValue => true in column configuration in the 'external' part, I get the error 	
"The requested configuration was not found (table: tablename, index: 0). Message: No valid handlers found for type: unknown".
What do I wrong?

Here is the code in the TCA configuration:

`'info_window_content' => [
            'exclude' => 1,
            'label' => 'LLL:EXT:go_maps_ext/Resources/Private/Language/locallang_db.xlf:tx_gomapsext_domain_model_address.info_window_content',
            'config' => [
                'type' => 'text',
                'cols' => 40,
                'rows' => 15,
                'eval' => 'trim',
                'enableRichtext' => 1,
                
            ],
            'external' => [
              0 => [
                'field' => 'InfoWindow',
                'xmlValue' => true,
              ]
            ],
            'defaultExtras' => 'richtext[]',
		],`

Thanks,
Chris

**Comment by fsuter** [comment]
Hi. Sorry for the delay in answering, I was on holiday. It looks like an exception happens when trying to get the node as XML, which is not properly caught and triggers the wrong error message. I can see that the source code does not have the proper try/catch blocks.

You can try to edit the XmlHandler class (file EXT:external_import/Classes/Handler/XmlHandler.php). You will find the method:
```
    protected function getXmlValue($node)
    {
        $innerHTML = '';
        $children = $node->childNodes;
        foreach ($children as $child) {
            $innerHTML .= $child->ownerDocument->saveXML($child);
        }
        return $innerHTML;
    }
```
which you can change to:
```
    protected function getXmlValue($node)
    {
        $innerHTML = '';
        $children = $node->childNodes;
        foreach ($children as $child) {
            try {
                $innerHTML .= $child->ownerDocument->saveXML($child);
            }
            catch (\Exception $e) {
                // Nothing to do
            }
        }
        return $innerHTML;
    }
```
The missing handler error should not appear anymore, which should let you see the results giving you a pointer into why External Import fails writing the value as a XML structure.

**Comment by fsuter** [comment]
I just stumbled on the same issue myself, while testing the external_import tutorial. The exception actually comes from the Core method `\TYPO3\CMS\Core\LinkHandling\LinkService::asString()`, which is invoked - in particular - while parsing rich-text fields (which is indeed your case). This method expects well-formed links, as indicated in the PHPdoc comments:
```
    /**
     * Returns a string interpretation of the link target, something like
     *
     *  - t3://page?uid=23&my=value#cool
     *  - https://www.typo3.org/
     *  - t3://file?uid=13
     *  - t3://folder?storage=2&identifier=/my/folder/
     *  - mailto:mac@safe.com
     *
     * @param array $parameters
     * @return string
     * @throws Exception\UnknownLinkHandlerException
     */
```
So I don't know what is the exact problem for you, but in my case it's a relative link like "/community/teams/documentation/", without protocol, which triggers the exception.

Now I need to think at how best to catch this exception, because there could be others and they must be caught in a meaningful and - if possible - helpful way.

**Comment by fsuter** [comment]
I must add that catching the exception properly will not solve your problem: the import will still be interrupted. So you will still have to check why this happens for you and how best to handle it. One possibility would be to parse the XML structure with one of the early hooks and correct/change the items that cause problem. Another could be to register a link handler for type "unknown" and handle the data as appropriate for your needs, although you would have to be wary about side effects on the Core in such a case (because all the handling of links goes through the LinkService class).

**Comment by fsuter** [comment]
I'm closing this issue, because I did what needs to be done in External Import. As I said earlier, this doesn't solve your problem, because it has to do with the data that you are working with. Dont hesitate to keep asking questions though.
