### ISSUE TITLE
Delete records the efficient way

### ISSUE THREAD

**Issue by webian** [cobwebch/external_import#88]
Hi @fsuter,
I'm searching for the more efficient way to delete local records if no more present in external source.

To simplify, actually I have one configuration to **insert/update** pages tree based on external source categories. This conf that runs every 5 minutes has `'disabledOperations' => 'delete'` because it only gets external records that has been updated after the last synchronization and I don't want that this config deletes all the local records that seems no more present in the external source just because they has not been recently updated externally. This config works good.

Instead, to **delete** pages that are no more present into the external source, I use a second configuration that gets only the ID of all the external records (even those not recently updated) and should then delete local records no more present in the external source. Here comes my confusion...
If I set this configuration `'disabledOperations' => 'insert,update'` then all the pages are deleted no matter what. This because here:
https://github.com/cobwebch/external_import/blob/241921218ea039ffafbaa4620c15c0ddc75f60b0/Classes/Step/StoreDataStep.php#L374
$updatedUids is empty because I disabled update in the config.

At this point I tried to allow update with `'disabledOperations' => 'insert'` and the delete works but the caches of all the pages are cleared because external_import instruct dataHandler to update all the uid:
https://github.com/cobwebch/external_import/blob/241921218ea039ffafbaa4620c15c0ddc75f60b0/Classes/Step/StoreDataStep.php#L304

Since I don't want that all the caches are cleared even if no external modifications are made, how can I achieve this?

**Comment by fsuter** [comment]
I don't think that this can be entirely automated. I had a similar scenario with news items and needed to create some custom code.

It could be something like this: add a field to the pages table which you fill with a fixed value during the import process (https://docs.typo3.org/typo3cms/extensions/external_import/Administration/Transformations/Index.html#value). For example, make it so that its default value is 0 and the import sets it to 1. Then you can use the `datamapPostProcess` hook to trigger a script which deletes all pages with an external id and that new field having a value of 0 (i.e. not inserted, nor updated). After having delete those pages, reset the flag to 0 for all pages, so that the next import starts with a clean slate again.

Would that work for you?

**Comment by webian** [comment]
Thanks for you help but I probably didn't get it. Following what I understood, I make this example...
Let's suppose the flag field is called `touch`.

The update is run for the first time. All local records are new and inserted with their field `touch` set to 1. The `datamapPostProcess` script doesn't delete records because all `touch`=1 and reset all `touch` field to 0. Everything is all right at this point, but then...

Let's simply suppose that nothing happens externally. The update is run for the second time. external_import doesn't find any new or updated external records because it's configured to query records changed since the last import. So `touch` remains 0 for all local records. The `datamapPostProcess` script deletes all local records because all have `touch`=0 but they exists externally.

Am I missing something?

**Comment by webian** [comment]
What I could do eventually is, after each insert/update, use `datamapPostProcess` and query all remote records IDs (e.g.: 1,4,7,12) and delete all local records with an SQL where `external_id NOT IN (1,4,7,12)`. Not elegant but should do the job.

Practically is the same as the initial second configuration (the one that should only delete local records) but bypassing external_import.

**Comment by fsuter** [comment]
Yes, that would work. There's no help but bypassing external_import in this case. As you found out, your second configuration could actually do the job, but you don't want the cache to be flushed, which can't be avoided because external_import relies on DataHandler.

**Comment by webian** [comment]
Thanks anyway for your great support! :+1:

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Hi there,

I have exactly the same scenario and thus a problem like webian. I want to delete event records that are missing in the source, but I don't want all others to get updated because due to clearing the cache it slows down every single event detail page.

Is it really not possible to make the extensions behaviour like one would expect: if 'disabledOperations' => 'insert,update' then it only deletes missing records but don't update or insert? Watching at the preview data, the data to be updated and deleted are split anyways in the storeDataStep. My modest skills say that you could empty everything under the "data" array and leave the "commands-delete" array.

I think it's quite undesired if all the data gets deleted although data from the external source clearly match with the DB. However, maybe atleast a new setting could help where you can choose how the delete operation behaves!? The datamapPostProcess solution is only a workaround. Don't like it much, because it bypasses the datahandler.

That said, your extension really rocks with all those possibilities and the very good support. Thank you!

Cheers! :)

**Comment by fsuter** [comment]
OK. I'll take another look at some point.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
That would be really great and save some ugly postprocess code. ;) Thanks!

**Comment by fsuter** [comment]
With the recent refactoring of the `StoreDataStep` it was quite easy to fix this behavior.
