### ISSUE TITLE
TX_news import Images

### ISSUE THREAD

**Issue by marexx** [cobwebch/external_import#89]
An other question, is it possible to manipulate a string before using it.
I get something like that:
Z:\Produktbilder\Fotos_Komplette Sammlung\Brötchen\Sesambrötchen_neu.jpg
\bbn-server\mavesoft\mavebake\Produktbilder\Fotos_Komplette Sammlung\Stangenware\Lattenkracher_NEU.jpg

for the images i want to use. So i have to trim everything but the filename. Is that possible?

**Comment by marexx** [comment]
so the Path Problem is solved with the linktransformation Class:
    public function absolutizeUrls($record, $index, $params): string
    {
        $host = $params['host'];
        $text = $record[$index];
        $basename = preg_replace('/^.+\\\\/', '', $text);      
        $text = $host.'/'.$basename;
        return $text;
    }

But how can i store the image?

**Comment by fsuter** [comment]
Storing the image is entirely up to you. You will need to use either a user function or a custom step. A future version of external_import may have some boilerplate code to help, but there's currently nothing available in that regard.

**Comment by marexx** [comment]
mmh. do you have an Idea for the following:
i got the filename in the import_csv and i got the image-files on the server. How can i connect those?

**Comment by fsuter** [comment]
If you want to do things cleanly, you need to create sys_file entries for each file, then connect to your imported records by creating sys_file_reference entries. However I have no practical experience for this, so I'm not sure where the best place is to do that. It could be a custom step, or one of the hooks (probably `datamapPostprocess`, because that's where you have the information about saved records).

**Comment by fsuter** [comment]
Any update on this? Can I close this issue?

**Comment by fsuter** [comment]
No further news, closing the issue.
